version: '3.8'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      SA_PASSWORD: "Your_password123"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
  
  accountmanagerapi:
    build:
      context: .
      dockerfile: AccountPhoneManager.API/Dockerfile
    environment:
      - ConnectionStrings__SqlServer=Server=sqlserver;User Id=sa;Password=Your_password123;TrustServerCertificate=True;
    depends_on:
      - sqlserver
    ports:
      - "8080:8080"